local AddOnName, AddOn, Util


describe("EffortPoints", function()
	setup(function()
		AddOnName, AddOn = loadfile("Test/TestSetup.lua")(true, 'Modules_EffortPoints')
		AddOnLoaded(AddOnName, true)
		Util = AddOn:GetLibrary('Util')
	end)

	teardown(function()
		After()
	end)

	describe("lifecycle", function()
		it("is disabled on startup", function()
			local module = AddOn:EffortPointsModule()
			assert(module)
			assert(module:IsEnabled())
		end)
		it("can be disabled", function()
			AddOn:ToggleModule("EffortPoints")
			local module = AddOn:EffortPointsModule()
			assert(module)
			assert(not module:IsEnabled())
		end)
		it("can be enabled", function()
			AddOn:ToggleModule("EffortPoints")
			local module = AddOn:EffortPointsModule()
			assert(module)
			assert(module:IsEnabled())
		end)
	end)

	describe("configuration", function()
		it("is built", function()
			local module = AddOn:EffortPointsModule()
			assert(module:BuildConfigOptions())
		end)
	end)
end)