local AddOnName, AddOn, Util


describe("Standings", function()
	setup(function()
		AddOnName, AddOn = loadfile("Test/TestSetup.lua")(true, 'Modules_LootSession')
		Util = AddOn:GetLibrary('Util')
		AddOnLoaded(AddOnName, true)
	end)

	teardown(function()
		After()
	end)

	describe("lifecycle", function()
		it("is disabled on startup", function()
			local module = AddOn:MasterLooterModule()
			assert(module)
			assert(not module:IsEnabled())
		end)
		it("can be enabled", function()
			AddOn:ToggleModule("MasterLooter")
			local module = AddOn:MasterLooterModule()
			assert(module)
			assert(module:IsEnabled())
		end)
		it("can be disabled", function()
			AddOn:ToggleModule("MasterLooter")
			local module = AddOn:MasterLooterModule()
			assert(module)
			assert(not module:IsEnabled())
		end)
	end)
end)