local AddOnName, AddOn, Util, Player, t

describe("Events", function()
	setup(function()
		AddOnName, AddOn = loadfile("Test/TestSetup.lua")(true, 'Core_Events')
		Util, Player = AddOn:GetLibrary('Util'), AddOn.Package('Models').Player
		AddOnLoaded(AddOnName, true)
		SetTime()
	end)
	teardown(function()
		print(Util.Objects.ToString( AddOn.Require('Core.Event').private.metricsRcv:Summarize()))
		print(Util.Objects.ToString( AddOn.Require('Core.Comm').private.metricsSend:Summarize()))
		print(Util.Objects.ToString( AddOn.Require('Core.Comm').private.metricsRecv:Summarize()))
		print(Util.Objects.ToString( AddOn.Require('Core.Comm').private.metricsFired:Summarize()))
		After()
	end)

	describe("basics", function()
		it("PlayerEnteringWorld", function()
			AddOn.player = Player:Get('Player2-Realm1')
			PlayerEnteredWorld()
			assert(not AddOn:IsMasterLooter())
			assert(#AddOn.playerData.gear > 0)
			assert(AddOn.playerData.ilvl >= 0)
		end)
		it("PlayerEnteringWorld", function()
			AddOn.player = Player:Get('Player1-Realm1')
			WoWAPI_FireEvent("GROUP_LEFT")
			assert(AddOn:IsMasterLooter())
			WoWAPI_FireEvent("PARTY_LEADER_CHANGED")
			assert(AddOn:IsMasterLooter())
			WoWAPI_FireEvent("PARTY_LOOT_METHOD_CHANGED")
			assert(AddOn:IsMasterLooter())
		end)
	end)
end)