local AddOnName, AddOn

describe("Util", function()
    setup(function()
        AddOnName, AddOn = loadfile("Test/TestSetup.lua")(true, 'Core_Util')
    end)
    teardown(function()
        After()
    end)

    describe("functions", function()
        it("Qualify", function()
            assert(AddOn:Qualify("Test") == format("%s_%s", AddOn.Constants.name, "Test"))
            assert(AddOn:Qualify("Test", "Another") == format("%s_%s_%s", AddOn.Constants.name, "Test", "Another"))
        end)
        it("UnitName", function()
            assert(AddOn:UnitName('foo-realm') == 'Foo-realm')
            assert(AddOn:UnitName('player') == 'Player1-Realm1')
            assert(AddOn:UnitName('Fluffy') == 'Fluffy-Realm1')
            assert(not AddOn:UnitName())
        end)
        it("UnitIsUnit", function()
            assert(not AddOn:UnitIsUnit(nil, nil))
            assert(not AddOn:UnitIsUnit('foo', nil))
            assert(not AddOn:UnitIsUnit(nil, 'bar'))

            assert(not AddOn:UnitIsUnit({name = nil}, {name = nil}))
            assert(not AddOn:UnitIsUnit(nil, {name = 'bar'}))
            assert(not AddOn:UnitIsUnit({name = 'foo'}, nil))

            assert(AddOn:UnitIsUnit('player', 'player') == 1)
            assert(AddOn:UnitIsUnit('Player', 'plaYer') == 1)
            assert(AddOn:UnitIsUnit('Player1-Realm1', 'Player1') == 1)
            assert(AddOn:UnitIsUnit('Player1-Realm1', 'Player1-Realm1') == 1)
            assert(AddOn:UnitIsUnit('Player1-Realm1', 'Player1') == 1)
        end)
        it("UnitClass", function()
            assert(AddOn:UnitClass("player") == 'WARRIOR')
            assert(AddOn:UnitClass("Eliovak") == 'ROGUE')
            assert(AddOn:UnitClass("Gnomechómsky-Atiesh") == 'WARLOCK')
            assert(AddOn:UnitClass("Fluffybunny") == 'HUNTER')
            assert(AddOn:UnitClass("noguid") == 'WARRIOR')
        end)
    end)
end)